name = "streamflix-api"
main = "worker.js"
compatibility_date = "2023-01-01"

[build]
command = "npm run build"

[[build.upload]]
format = "service-worker"

[vars]
# No secrets here - API keys are hardcoded in the worker for security
